/**
 * Generate comprehensive DESIGN.md content from design analysis data
 * @param {Object} designData - Comprehensive analyzed design data
 * @returns {string} DESIGN.md markdown content
 */
function generateDesignMD(designData) {
  const {
    url,
    visualTheme,
    colorPalette,
    typography,
    components,
    layout,
    elevation,
    motion,
    accessibility,
    designPatterns,
    responsive,
    agentPrompts,
    cssFramework,
    meta,
    structureHints,
    dosAndDonts,
  } = designData;

  let md = '';

  // ============================================================
  // HEADER
  // ============================================================
  md += `# DESIGN.md\n\n`;
  md += `> Auto-generated design system documentation\n`;
  md += `> Source: [${url}](${url})\n`;
  if (meta.title) md += `> Site: ${meta.title}\n`;
  md += `> Generated by designermd\n\n`;
  md += `---\n\n`;

  // ============================================================
  // 1. VISUAL THEME AND ATMOSPHERE
  // ============================================================
  md += `## 1. Visual theme and atmosphere\n\n`;

  if (visualTheme.summary) {
    md += `${visualTheme.summary}\n\n`;
  }

  // Atmosphere & mood summary
  const atmosphereParts = [];
  if (visualTheme.atmosphere) atmosphereParts.push(visualTheme.atmosphere);
  if (visualTheme.mood) atmosphereParts.push(visualTheme.mood);
  if (visualTheme.density) atmosphereParts.push(visualTheme.density);
  if (visualTheme.personality) atmosphereParts.push(visualTheme.personality);

  if (atmosphereParts.length > 0) {
    md += `${atmosphereParts.join(', ')}.`;
  }

  if (visualTheme.framework) {
    md += `\n\n**Framework:** ${visualTheme.framework}\n`;
  }

  // Design patterns summary
  const patternParts = [];
  if (designPatterns.layoutPattern !== 'freeform') patternParts.push(`Layout: ${designPatterns.layoutPattern}`);
  if (designPatterns.navigationPattern !== 'topbar') patternParts.push(`Navigation: ${designPatterns.navigationPattern}`);
  if (designPatterns.cardStyle !== 'bordered') patternParts.push(`Cards: ${designPatterns.cardStyle}`);
  if (designPatterns.visualStyle !== 'clean') patternParts.push(`Style: ${designPatterns.visualStyle}`);
  if (designPatterns.componentDensity !== 'comfortable') patternParts.push(`Density: ${designPatterns.componentDensity}`);
  if (designPatterns.designLanguage !== 'modern') patternParts.push(`Language: ${designPatterns.designLanguage}`);

  if (patternParts.length > 0) {
    md += `\n\n**Design patterns:** ${patternParts.join(' · ')}\n`;
  }

  // Detected components
  if (structureHints) {
    const detectedComponents = [];
    if (structureHints.hasNavigation) detectedComponents.push('Navigation');
    if (structureHints.hasHero) detectedComponents.push('Hero');
    if (structureHints.hasGrid) detectedComponents.push('Grid');
    if (structureHints.hasCards) detectedComponents.push('Cards');
    if (structureHints.hasFooter) detectedComponents.push('Footer');
    if (structureHints.hasSidebar) detectedComponents.push('Sidebar');
    if (structureHints.hasForm) detectedComponents.push('Forms');
    if (structureHints.hasModal) detectedComponents.push('Modal');
    if (structureHints.hasTable) detectedComponents.push('Tables');
    if (structureHints.hasBadge) detectedComponents.push('Badges');
    if (structureHints.hasAvatar) detectedComponents.push('Avatars');
    if (structureHints.hasTabs) detectedComponents.push('Tabs');
    if (structureHints.hasDropdown) detectedComponents.push('Dropdowns');
    if (structureHints.hasToggle) detectedComponents.push('Toggles');
    if (structureHints.hasNotification) detectedComponents.push('Notifications');

    if (detectedComponents.length > 0) {
      md += `\n\n**Detected components:** ${detectedComponents.join(', ')}\n`;
    }
  }

  md += `\nThis section answers "why does it look like this?" The other 8 sections tell you what. This one tells you why.\n\n`;
  md += `---\n\n`;

  // ============================================================
  // 2. COLOR PALETTE AND ROLES
  // ============================================================
  md += `## 2. Color palette and roles\n\n`;

  // Semantic colors table
  md += `### Semantic colors\n\n`;
  md += `| Role              | Token              | Value     | Preview |\n`;
  md += `|-------------------|--------------------|-----------|---------|\n`;

  for (const [role, data] of Object.entries(colorPalette.semantic)) {
    const preview = `▮`;
    md += `| ${role.padEnd(17)} | ${data.token.padEnd(18)} | ${data.value.padEnd(9)} | ${preview} |\n`;
  }

  // Gradient information
  if (colorPalette.gradients.length > 0) {
    md += `\n### Gradients\n\n`;
    colorPalette.gradients.slice(0, 3).forEach((g, i) => {
      md += `${i + 1}. \`${g}\`\n`;
    });
  }

  // Accent colors
  if (colorPalette.accents.length > 0) {
    md += `\n### Accent colors\n\n`;
    colorPalette.accents.forEach((a) => {
      md += `- \`--${a.token}\`: ${a.value}\n`;
    });
  }

  // Color harmony
  md += `\n### Color analysis\n\n`;
  md += `- **Harmony:** ${colorPalette.harmony}\n`;
  md += `- **Contrast ratio:** ${colorPalette.contrast}\n`;
  if (colorPalette.neutrals.length > 0) {
    md += `- **Neutral scale:** ${colorPalette.neutrals.length} tones detected\n`;
  }

  md += `\nEvery color is defined with its hex value and its semantic role. The file doesn't just say "blue." It says what that blue does.\n\n`;
  md += `---\n\n`;

  // ============================================================
  // 3. TYPOGRAPHY RULES
  // ============================================================
  md += `## 3. Typography rules\n\n`;

  // Font families
  if (typography.fonts.length > 0) {
    const displayFonts = typography.fonts.filter((f) => !f.startsWith('var('));
    if (displayFonts.length > 0) {
      md += `**Fonts:** ${displayFonts.slice(0, 3).join(', ')}\n\n`;
    }
  }
  if (typography.codeFont) {
    md += `**Code font:** ${typography.codeFont}\n\n`;
  }

  // Font weights used
  if (typography.fontWeights.length > 0) {
    md += `**Font weights in use:** ${typography.fontWeights.join(', ')}\n\n`;
  }

  // Text transforms
  if (Object.keys(typography.textTransforms).length > 0) {
    md += `**Text transforms:** ${Object.entries(typography.textTransforms).map(([k, v]) => `${k} (${v}×)`).join(', ')}\n\n`;
  }

  // Hierarchy table
  md += `### Type scale\n\n`;
  md += `| Level          | Size  | Weight | Line-height | Letter-spacing |\n`;
  md += `|----------------|-------|--------|-------------|----------------|\n`;

  for (const level of typography.hierarchy) {
    md += `| ${level.level.padEnd(14)} | ${(level.size || '').padEnd(5)} | ${String(level.weight || '').padEnd(6)} | ${String(level.lineHeight || '').padEnd(11)} | ${(level.letterSpacing || '0').padEnd(14)} |\n`;
  }

  // Letter spacing & line height observations
  if (typography.letterSpacingScale.length > 0) {
    const uniqueTracking = [...new Set(typography.letterSpacingScale)].slice(0, 5);
    md += `\n**Letter-spacing values:** ${uniqueTracking.join(', ')}\n`;
  }
  if (typography.lineHeightScale.length > 0) {
    const uniqueHeights = [...new Set(typography.lineHeightScale)].slice(0, 5);
    md += `**Line-heights:** ${uniqueHeights.join(', ')}\n`;
  }

  md += `\nFont family, size hierarchy, weight, line-height, and letter-spacing, all in a table, with context for which one goes where.\n\n`;
  md += `---\n\n`;

  // ============================================================
  // 4. COMPONENT STYLES
  // ============================================================
  md += `## 4. Component styles\n\n`;

  for (const [name, style] of Object.entries(components)) {
    md += `### ${name}\n\n`;

    // Core properties
    const props = [];
    if (style.background) props.push(`Background: ${style.background}`);
    if (style.backgroundColor) props.push(`Background: ${style.backgroundColor}`);
    if (style.padding) props.push(`Padding: ${style.padding}`);
    if (style.borderRadius) props.push(`Border-radius: ${style.borderRadius}`);
    if (style.height) props.push(`Height: ${style.height}`);
    if (style.minHeight) props.push(`Min-height: ${style.minHeight}`);
    if (style.gap) props.push(`Gap: ${style.gap}`);
    if (style.color) props.push(`Text color: ${style.color}`);
    if (style.textTransform) props.push(`Text transform: ${style.textTransform}`);

    if (style.fontSize && style.fontWeight) {
      props.push(`Font: ${style.fontSize}, weight ${style.fontWeight}`);
    } else if (style.fontSize) {
      props.push(`Font-size: ${style.fontSize}`);
    } else if (style.fontWeight) {
      props.push(`Font-weight: ${style.fontWeight}`);
    }

    if (style.border) props.push(`Border: ${style.border}`);
    if (style.boxShadow) props.push(`Shadow: ${style.boxShadow}`);

    props.forEach((p) => md += `- ${p}\n`);

    // States
    if (style.hover) {
      md += `- Hover: ${style.hover}\n`;
    } else if (name.toLowerCase().includes('button')) {
      md += `- Hover: brightness(1.15)\n`;
    }

    if (style.focus) {
      md += `- Focus: ${style.focus}\n`;
    } else if (name.toLowerCase().includes('button') || name.toLowerCase().includes('input')) {
      md += `- Focus: 2px ring with accent color\n`;
    }

    if (style.disabled) {
      md += `- Disabled: ${style.disabled}\n`;
    } else if (name.toLowerCase().includes('button')) {
      md += `- Disabled: opacity 0.5, pointer-events none\n`;
    }

    md += `\n`;
  }

  md += `Style definitions for core elements including all states. Padding, border-radius, shadow, hover/focus/disabled behavior.\n\n`;
  md += `---\n\n`;

  // ============================================================
  // 5. LAYOUT PRINCIPLES
  // ============================================================
  md += `## 5. Layout principles\n\n`;
  md += `### Spacing\n\n`;
  md += `- Base unit: ${layout.baseUnit}\n`;
  md += `- Spacing scale: ${layout.spacingScale.join(', ')}\n`;
  if (layout.containerPadding) {
    md += `- Container padding: ${layout.containerPadding}\n`;
  }
  md += `- Max content width: ${layout.maxContentWidth}\n`;
  md += `- Section gap: ${layout.sectionGap}\n`;

  md += `\n### Border radius\n\n`;
  md += `| Element         | Radius    |\n`;
  md += `|-----------------|----------|\n`;
  for (const [element, radius] of Object.entries(layout.borderRadiusScale)) {
    md += `| ${element.charAt(0).toUpperCase().concat(element.slice(1)).padEnd(15)} | ${radius.padEnd(8)} |\n`;
  }

  md += `\n### Grid system\n\n`;
  md += `- Layout method: ${layout.gridSystem}\n`;

  md += `\nSpacing scale, grid system, container widths, whitespace approach, and border-radius scale.\n\n`;
  md += `---\n\n`;

  // ============================================================
  // 6. DEPTH AND ELEVATION
  // ============================================================
  md += `## 6. Depth and elevation\n\n`;
  md += `| Level     | Usage          | Shadow                                        |\n`;
  md += `|-----------|----------------|-----------------------------------------------|\n`;

  for (const level of elevation.levels) {
    const shadowPreview = level.shadow.length > 47 ? level.shadow.substring(0, 44) + '...' : level.shadow;
    md += `| ${level.level.padEnd(9)} | ${level.usage.padEnd(14)} | ${shadowPreview.padEnd(45)} |\n`;
  }

  // Additional depth notes
  const depthNotes = [];
  if (elevation.borderDepth) depthNotes.push('Uses **borders** (not shadows) for depth separation');
  if (elevation.glassEffects) depthNotes.push('Uses **glass/blur effects** (backdrop-filter) for overlay surfaces');
  if (elevation.blurEffects) depthNotes.push('Backdrop blur is applied to create depth layering');

  if (depthNotes.length > 0) {
    md += `\n${depthNotes.join('. ')}.\n`;
  }

  md += `\nThe shadow system, surface hierarchy, and elevation levels. Which layer gets which shadow, with specific rgba values.\n\n`;
  md += `---\n\n`;

  // ============================================================
  // 7. MOTION SYSTEM
  // ============================================================
  md += `## 7. Motion and animation\n\n`;
  md += `**Motion style:** ${motion.motionStyle}\n\n`;

  if (motion.transitions.length > 0) {
    md += `### Transitions\n\n`;
    motion.transitions.forEach((t) => md += `- ${t}\n`);
    md += '\n';
  }

  if (motion.animations.length > 0) {
    md += `### Keyframe animations\n\n`;
    motion.animations.forEach((a) => md += `- ${a}\n`);
    md += '\n';
  }

  if (motion.durationScale.length > 0) {
    md += `**Durations:** ${motion.durationScale.join(', ')}\n`;
  }
  if (motion.easingScale.length > 0) {
    md += `**Easing:** ${motion.easingScale.join(', ')}\n`;
  }

  md += `\n**Accessibility:** ${motion.hasReducedMotion ? '✅ Respects `prefers-reduced-motion`' : '⚠️ No reduced-motion support detected'}\n\n`;
  md += `---\n\n`;

  // ============================================================
  // 8. DO'S AND DON'TS
  // ============================================================
  md += `## 8. Do's and don'ts\n\n`;
  md += `Design boundaries and anti-patterns. The "don't" list matters at least as much as the "do" list.\n\n`;

  md += `### Do\n\n`;
  for (const item of dosAndDonts.dos) {
    md += `- ${item}\n`;
  }

  md += `\n### Don't\n\n`;
  for (const item of dosAndDonts.donts) {
    md += `- ${item}\n`;
  }

  md += `\n`;
  md += `---\n\n`;

  // ============================================================
  // 9. RESPONSIVE BEHAVIOR
  // ============================================================
  md += `## 9. Responsive behavior\n\n`;
  md += `### Breakpoints\n\n`;
  md += `| Breakpoint | Width   | Behavior                                   |\n`;
  md += `|------------|---------|--------------------------------------------|\n`;

  for (const bp of responsive.breakpoints) {
    md += `| ${bp.name.padEnd(10)} | ${bp.width.padEnd(7)} | ${bp.behavior.padEnd(42)} |\n`;
  }

  md += `\n### Touch and mobile\n\n`;
  md += `- Touch target minimum: ${responsive.touchTarget}\n`;
  md += `- Minimum font size on mobile: ${responsive.mobileMinFontSize}\n`;
  md += `- Fluid typography: ${responsive.fluidTypography ? '✅ Yes (using clamp())' : '❌ No'}\n`;
  md += `- Container queries: ${responsive.containerQueries ? '✅ Yes' : '❌ No'}\n`;
  md += `- Mobile-first: ${responsive.mobileFirst ? '✅ Yes' : '❌ No (desktop-first)'}\n`;

  md += `\nBreakpoints, touch target sizes, and how things collapse on smaller screens.\n\n`;
  md += `---\n\n`;

  // ============================================================
  // 10. ACCESSIBILITY
  // ============================================================
  md += `## 10. Accessibility\n\n`;

  const a11yChecks = [];
  if (accessibility.focusStyles) a11yChecks.push({ label: 'Focus indicators', pass: true });
  if (accessibility.outlineReset) a11yChecks.push({ label: 'Focus outline removed', pass: false });
  if (accessibility.skipLinks) a11yChecks.push({ label: 'Skip navigation', pass: true });
  if (accessibility.ariaLandmarks) a11yChecks.push({ label: 'ARIA landmarks', pass: true });
  if (accessibility.reducedMotionSupport) a11yChecks.push({ label: 'Reduced motion support', pass: true });
  if (accessibility.highContrastSupport) a11yChecks.push({ label: 'High contrast mode', pass: true });
  if (accessibility.srOnlyClass) a11yChecks.push({ label: 'Screen reader utilities', pass: true });

  if (a11yChecks.length > 0) {
    md += `| Feature                | Status |\n`;
    md += `|------------------------|--------|\n`;
    a11yChecks.forEach((check) => {
      md += `| ${check.label.padEnd(22)} | ${check.pass ? '✅' : '❌'}     |\n`;
    });
  }

  md += `\n`;
  md += `---\n\n`;

  // ============================================================
  // 11. AGENT PROMPT GUIDE
  // ============================================================
  md += `## 11. Agent prompt guide\n\n`;
  md += `### Quick palette reference\n\n`;
  md += `\`${agentPrompts.quickPalette}\`\n\n`;

  if (agentPrompts.componentPrompts.length > 0) {
    md += `### Component prompts\n\n`;
    agentPrompts.componentPrompts.forEach((p, i) => {
      md += `${i + 1}. ${p}\n\n`;
    });
  }

  if (agentPrompts.pagePrompts.length > 0) {
    md += `### Page templates\n\n`;
    agentPrompts.pagePrompts.forEach((p, i) => {
      md += `${i + 1}. ${p}\n\n`;
    });
  }

  // Additional quick prompts based on detected patterns
  md += `### Design system commands\n\n`;

  if (designPatterns.navigationPattern === 'sidebar') {
    md += `- "Create a sidebar navigation" → Collapsible sections, active state with accent color,\n`;
    md += `  240px width, icon + label pattern\n`;
  }

  if (designPatterns.cardStyle === 'shadowed') {
    md += `- "Create a card grid" → Cards with shadow for depth, ${layout.spacingScale[1] || 16}px gap,\n`;
    md += `  rounded corners, hover lift effect\n`;
  }

  if (designPatterns.layoutPattern === 'grid') {
    md += `- "Build a dashboard layout" → CSS Grid with ${layout.spacingScale[1] || 16}px gap,\n`;
    md += `  responsive columns, accent color for key metrics\n`;
  }

  md += `- "Create a form" → Stacked inputs with ${components['Input']?.borderRadius || '6px'} border-radius,\n`;
  md += `  accent color for focus state, error state with destructive color\n`;

  md += `\nA quick-reference color summary and ready-to-use component prompts for the agent.\n\n`;

  return md;
}

module.exports = { generateDesignMD };
